name: myfm
include:
  - shared.yml
services:

  icecast:
    build: ./icecast-kh-docker
    container_name: icecast-fsg
    volumes:
      - ./icecast-kh-docker/config:/home/icecast/config
      - ./icecast-kh-docker/log:/home/icecast/log
      - ./icecast-kh-docker/docker-entrypoint.sh:/home/icecast/docker-entrypoint.sh
    restart: unless-stopped
    environment:
      - IC_LOCATION=${IC_LOCATION:-Germany}
      - IC_ADMIN_USER=${IC_ADMIN_USER:-admin}
      - IC_ADMIN_EMAIL=${IC_ADMIN_EMAIL:-admin@localhost}
      - IC_SOURCE_PASSWORD=${IC_SOURCE_PASSWORD:-hackme}
      - IC_ADMIN_PASSWORD=${IC_ADMIN_PASSWORD:-hackme}
      - IC_HOSTNAME=${IC_HOSTNAME:-localhost}
      # - IC_MOUNT_PASSWORD=
      #- IC_RELAY_SERVER=stream.urdt.lv
    entrypoint: /home/icecast/docker-entrypoint.sh
    command: "-c /home/icecast/config/icecast.xml"
    ports:
      - "8000:8000"

  app:
    build: ./app
    ports:
      - "8090:80"
    depends_on:
      - firebird
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./data:/var/lib/firebird/data
      - /var/data/music:/var/data/music
      - ./app:/home/shiva/bin
      - ./indexer:/home/shiva/bin/indexer
      - opt-volume:/opt
    environment:
      - IC_ADMIN_USER=${IC_ADMIN_USER:-admin}
      - IC_ADMIN_PASSWORD=${IC_ADMIN_PASSWORD:-hackme}
      - IC_SOURCE_PASSWORD=${IC_SOURCE_PASSWORD:-hackme}
      - FIREBIRD_ROOT_PASSWORD=${FIREBIRD_ROOT_PASSWORD:-masterkey}
      - FIREBIRD_USER=${FIREBIRD_USER:-shiva}
      - FIREBIRD_PASSWORD=${FIREBIRD_PASSWORD:-shiva}
      - APP_USER=${APP_USER:-shiva}
      - APP_PASSWORD=${APP_PASSWORD:-shiva}
      - FIREBIRD_DATABASE=${FIREBIRD_DATABASE:-iceshake.fdb}

    command: >
      sh -c "
      cp ~/app/ices ~/bin && 
      cd ~/bin && 
      envsubst < /var/lib/firebird/data/ices.conf > /tmp/ices.conf &&
      envsubst < /var/lib/firebird/data/iceshake.ini.dist > /var/lib/firebird/data/iceshake.ini &&
      ./ices -c /tmp/ices.conf && 
      sudo nginx && 
      ./init.sh &&     
      exec gunicorn -b 0.0.0.0:8080 main:application"
    # command: sh -c "tail -f /dev/null"

