FROM python:3.13-trixie AS build
LABEL authors="frank"
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git build-essential cmake libmp3lame-dev libflac-dev libxml2-dev libshout-dev libvorbis-dev libogg-dev libfaad-dev libpython3-dev libperl-dev
RUN git clone https://github.com/franksgg/ices0.git
WORKDIR /ices0
RUN mkdir "build"
#RUN cmake --help
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
      -DWITH_XML=ON -DWITH_PYTHON=ON -DWITH_PERL=ON -DWITH_LAME=ON \
      -DWITH_VORBIS=ON -DWITH_FAAD=ON -DWITH_FLAC=ON
RUN cmake --build build

FROM python:3.13-trixie

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get -y upgrade && apt-get install -y sudo \
    psmisc libmp3lame-dev libflac-dev libxml2-dev \
    libshout-dev libvorbis-dev libogg-dev libfaad-dev libshout-dev libpython3-dev libperl-dev \
    libtommath1 gunicorn nginx\
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*



ARG USERNAME=shiva
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG USER_PW=shiva



RUN useradd --create-home --shell /bin/bash  $USERNAME  && \
    mkdir -p /home/$USERNAME/app && \
    chown $USERNAME:$USERNAME /home/$USERNAME/app && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME   &&\
    chmod 0440 /etc/sudoers.d/$USERNAME

# install dependencies
RUN pip install --upgrade pip
WORKDIR /home/$USERNAME/app
RUN sed -i 's/www-data/shiva/g'  /etc/nginx/nginx.conf
USER $USERNAME
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY --from=build --chown=shiva:shiva /ices0/build/src/ices ices
RUN touch y
WORKDIR /home/$USERNAME/bin
CMD [ "python", "main.py" ]