
SET SQL DIALECT 3; 

/* CREATE DATABASE 'firebird:/var/lib/firebird/data/iceshake.fdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8; */


/* Domain definitions */
CREATE DOMAIN D_BIGINT AS BIGINT;
CREATE DOMAIN D_BOOLEAN AS BOOLEAN;
CREATE DOMAIN D_C128 AS CHAR(128) NOT NULL;
CREATE DOMAIN D_DATE AS DATE;
CREATE DOMAIN D_DOUBLE AS DOUBLE PRECISION;
CREATE DOMAIN D_FK AS BIGINT;
CREATE DOMAIN D_ID AS BIGINT NOT NULL;
CREATE DOMAIN D_IMAGE AS BLOB SUB_TYPE 0 SEGMENT SIZE 80;
CREATE DOMAIN D_INT AS INTEGER;
CREATE DOMAIN D_SMALLINT AS SMALLINT;
CREATE DOMAIN D_TEXT AS BLOB SUB_TYPE TEXT SEGMENT SIZE 80;
CREATE DOMAIN D_TIME AS TIME;
CREATE DOMAIN D_TIMESTAMP AS TIMESTAMP;
CREATE DOMAIN D_VC10 AS VARCHAR(10);
CREATE DOMAIN D_VC1024 AS VARCHAR(1024);
CREATE DOMAIN D_VC128 AS VARCHAR(128);
CREATE DOMAIN D_VC20 AS VARCHAR(20);
CREATE DOMAIN D_VC256 AS VARCHAR(256);
CREATE DOMAIN D_VC32 AS VARCHAR(32);
CREATE DOMAIN D_VC40 AS VARCHAR(40);
CREATE DOMAIN D_VC512 AS VARCHAR(512);
CREATE DOMAIN D_VCLONG AS VARCHAR(8000);
CREATE DOMAIN ID3_TAG AS CHAR(4);
COMMIT WORK;

/* Table: ACTPOS, Owner: SYSDBA */
CREATE TABLE ACTPOS (AP D_ID,
        STARTTIME D_TIME,
        WP D_BIGINT,
        FKRADIO D_FK DEFAULT 1 NOT NULL,
        ID D_FK DEFAULT 1 NOT NULL,
CONSTRAINT PK_ACTPOS PRIMARY KEY (ID));

/* Table: ACT_TRACK, Owner: SYSDBA */
CREATE TABLE ACT_TRACK (ID D_ID NOT NULL,
        TNR D_FK,
        STARTTIME D_TIME,
CONSTRAINT PK_ACT_TRACK PRIMARY KEY (ID));

/* Table: ALBUMS, Owner: SYSDBA */
CREATE TABLE ALBUMS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC128 NOT NULL,
        PYEAR D_SMALLINT,
        FK_IMAGE D_FK,
        ARTIST D_VC256,
        TIDID D_VC128,
PRIMARY KEY (ID));

/* Table: ALLFRAMES, Owner: SYSDBA */
CREATE TABLE ALLFRAMES (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        FK_TRACK D_FK,
        FRAME ID3_TAG NOT NULL,
        CONTENT D_VCLONG,
        FK_IMAGE D_FK,
        FK_LYRICS D_FK,
CONSTRAINT PK_ALLFRAMES PRIMARY KEY (ID));

/* Table: ARTISTS, Owner: SYSDBA */
CREATE TABLE ARTISTS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC256 NOT NULL,
        EVENTS D_VC256,
        FK_IMAGE D_FK,
        TIDID D_VC128,
PRIMARY KEY (ID));

/* Table: FORMAT, Owner: SYSDBA */
CREATE TABLE FORMAT (ID D_ID NOT NULL,
        NAME D_VC20,
CONSTRAINT PK_FORMAT PRIMARY KEY (ID));

/* Table: HISTORY, Owner: SYSDBA */
CREATE TABLE HISTORY (ZEIT D_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        TNR D_FK,
        TRACK D_VC256,
        ID D_BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
PRIMARY KEY (ID));

/* Table: ID3_TAGS, Owner: SYSDBA */
CREATE TABLE ID3_TAGS (FRAME ID3_TAG NOT NULL,
        DESCRIPTION D_VC256,
        GROUP_ID D_FK,
CONSTRAINT PK_ID3_TAGS PRIMARY KEY (FRAME));

/* Table: ID3_TYPES, Owner: SYSDBA */
CREATE TABLE ID3_TYPES (ID D_BIGINT NOT NULL,
        NAME D_VC20,
CONSTRAINT PK_ID3_TYPES PRIMARY KEY (ID));

/* Table: IMAGES, Owner: SYSDBA */
CREATE TABLE IMAGES (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        SOURCE D_VC256,
        IMAGE D_IMAGE,
        MIMETYPE D_VC128,
        HINT D_VC256,
        TIDID D_VC128,
        CRC32 D_BIGINT,
        ADDED D_TIMESTAMP,
CONSTRAINT PK_IMAGES PRIMARY KEY (ID));

/* Table: IUSERS, Owner: SYSDBA */
CREATE TABLE IUSERS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC128 NOT NULL,
        PASSWORD D_VC128 NOT NULL,
        IADMIN D_INT NOT NULL,
CONSTRAINT PK_IUSERS PRIMARY KEY (ID));

/* Table: LYRICS, Owner: SYSDBA */
CREATE TABLE LYRICS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        TEXT D_TEXT NOT NULL,
        SOURCE D_VC256,
PRIMARY KEY (ID));

/* Table: MUSICIANS, Owner: SYSDBA */
CREATE TABLE MUSICIANS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VCLONG,
CONSTRAINT PK_MUSICIANS PRIMARY KEY (ID));

/* Table: MUSIK, Owner: SYSDBA */
CREATE TABLE MUSIK (NAME D_VC40,
        TITEL D_VC40,
        JAHR D_SMALLINT,
        TONTRAEGER CHAR(9),
        NUMMER D_SMALLINT,
        MUSIKER D_VC40,
        M1 D_VC40,
        M2 D_VC40,
        M3 D_VC40,
        M4 D_VC40,
        M6 D_VC40,
        M7 D_VC40,
        M8 D_VC40,
        M9 D_VC40,
        M10 D_VC40,
        M11 D_VC40,
        M12 D_VC40);

/* Table: NDELAY, Owner: SYSDBA */
CREATE TABLE NDELAY (ID D_ID NOT NULL,
        DURATION D_SMALLINT,
CONSTRAINT PK_NDELAY PRIMARY KEY (ID));

/* Table: PARTICIPANTS, Owner: SYSDBA */
CREATE TABLE PARTICIPANTS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        FK_TRACK D_FK,
        FK_WHAT D_FK,
        FK_WHO D_FK,
CONSTRAINT PK_PARTICIPANTS PRIMARY KEY (ID));

/* Table: PL, Owner: SYSDBA */
CREATE TABLE PL (ID D_ID,
        FK_TRACK D_FK,
        FK_RADIO D_FK DEFAULT 1 NOT NULL,
CONSTRAINT PK_PL PRIMARY KEY (ID));

/* Table: RADIOS, Owner: SYSDBA */
CREATE TABLE RADIOS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC40,
CONSTRAINT PK_RADIOS PRIMARY KEY (ID));

/* Table: SESSIONS, Owner: SYSDBA */
CREATE TABLE SESSIONS (SESSION_ID D_C128 NOT NULL,
        ATIME D_TIMESTAMP DEFAULT current_timestamp NOT NULL,
        DATA D_TEXT,
        DATA2 D_TEXT,
CONSTRAINT PK_SESSIONS PRIMARY KEY (SESSION_ID));

/* Table: SYSDATA, Owner: SYSDBA */
CREATE TABLE SYSDATA (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        PLMAX D_BIGINT,
        WLMAX D_BIGINT,
        IMGSRC D_SMALLINT DEFAULT 1 NOT NULL,
        WEATHER D_BOOLEAN,
        SILENCE D_SMALLINT,
        WURL D_VC1024,
        SURL D_VC1024,
        SUSER D_VC32,
        SPW D_VC32,
        WUSER D_VC32,
        WPW D_VC32,
CONSTRAINT PK_SYSDATA PRIMARY KEY (ID));

/* Table: TASK, Owner: SYSDBA */
CREATE TABLE TASK (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        TASK D_VCLONG,
CONSTRAINT PK_TASK PRIMARY KEY (ID));

/* Table: TIDAL, Owner: SYSDBA */
CREATE TABLE TIDAL (ID D_VC10 NOT NULL,
        TYPE D_VC20,
        ARTIST D_VC512,
        TITLE D_VC512,
        ADDED D_TIMESTAMP,
        URL D_VCLONG);

/* Table: TIDALINFO, Owner: SYSDBA */
CREATE TABLE TIDALINFO (ID D_ID NOT NULL,
        TITLE D_VC256,
        ARTIST D_VC256,
        ALBUM D_VC256,
        GONE D_INT,
        LEN D_INT,
        PYEAR D_VC128,
        IMGSRC D_VC256,
        IMG D_IMAGE,
CONSTRAINT PK_TIDALINFO PRIMARY KEY (ID));

/* Table: TRACKS, Owner: SYSDBA */
CREATE TABLE TRACKS (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        PATH D_VC256 NOT NULL,
        TITLE D_VC128,
        BITRATE D_INT,
        FILE_SIZE D_BIGINT,
        LEN D_INT,
        NUMBER D_SMALLINT,
        ALBUM_PK D_FK,
        ARTIST_PK D_FK,
        LYRICS_PK D_FK,
        PYEAR D_SMALLINT,
        VOTES D_BIGINT DEFAULT 0,
        SAMPLERATE D_INT,
        IMAGE_PK D_FK,
        TIDID D_VC128,
PRIMARY KEY (ID),
UNIQUE (PATH));

/* Table: WL, Owner: SYSDBA */
CREATE TABLE WL (ID D_ID,
        FK_TRACK D_FK,
        FK_RADIO D_FK DEFAULT 1 NOT NULL);

/* Table: cddbALBUMS, Owner: SYSDBA */
CREATE TABLE "cddbALBUMS" (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC256 NOT NULL,
        PYEAR D_SMALLINT,
        FK_IMAGE D_FK,
        ARTIST D_VC128,
        DISCID D_VC20,
        TRACKS D_SMALLINT,
        FK_ARTIST D_FK,
CONSTRAINT "PK_cddbALBUMS_1" PRIMARY KEY (ID));

/* Table: cddbARTISTS, Owner: SYSDBA */
CREATE TABLE "cddbARTISTS" (ID D_ID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        NAME D_VC256 NOT NULL,
        EVENTS D_VC256,
        FK_IMAGE D_FK,
CONSTRAINT "PK_cddbARTISTS_1" PRIMARY KEY (ID));

COMMIT WORK;

SET TERM ^ ;

/* Stored functions headers */
CREATE OR ALTER FUNCTION ACTARTIST RETURNS D_VC256
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION ACTNAME RETURNS D_VC256
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION ACTTIME RETURNS D_VC40
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION ACTTITLE RETURNS D_VC256
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION ACTTRACK RETURNS D_VC256
AS 
BEGIN END ^

CREATE OR ALTER FUNCTION DAYNAME RETURNS CHAR(2) CHARACTER SET UTF8
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION NEXTPAUSE RETURNS D_VC256
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION NEXTTRACK RETURNS D_VC256
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION TNR (RID D_ID)
RETURNS D_FK
AS 
BEGIN END ^
CREATE OR ALTER FUNCTION TO_DATE (DATESTR CHAR(10) CHARACTER SET UTF8)
RETURNS DATE
AS 
BEGIN END ^


COMMIT WORK^


/* Stored procedures headers */
CREATE OR ALTER PROCEDURE ADDPNGIMAGE (IMAGE D_IMAGE,
AID D_ID,
OVERWRITE D_BOOLEAN = false)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE ALBUMLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE ALBUMLISTBYID (AID D_FK)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE ARTISTLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE ARTISTLISTBYID (AID D_FK)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE BEW (INCVAL TYPE OF D_BIGINT)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE DECPOS AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE DROP_ALL AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE FILLHINT AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE FILLYEARS RETURNS (YYEAR TYPE OF D_SMALLINT)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GETMETA RETURNS (TITLE D_VC256,
ARTIST D_VC256,
ALBUM D_VC256,
LEN D_INT,
PYEAR D_VC128,
PERCENT D_INT,
ATIME D_INT,
IMGSRC D_VC256,
IMG D_IMAGE,
TEMP D_DOUBLE,
HUM D_DOUBLE,
WIND D_DOUBLE,
VERBRAUCH D_DOUBLE,
PRODUKTION D_DOUBLE,
CINFO D_VC128)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GETMETA2 RETURNS (TITLE D_VC256,
ARTIST D_VC256,
ALBUM D_VC256,
LEN D_INT,
PYEAR D_VC128,
PERCENT D_INT,
ATIME D_INT,
IMGSRC D_VC256,
IMG D_IMAGE,
TEMP D_DOUBLE,
HUM D_DOUBLE,
WIND D_DOUBLE,
VERBRAUCH D_DOUBLE,
PRODUKTION D_DOUBLE,
CINFO D_VC128)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GETSUN RETURNS (SUNRISE D_TIME,
SUNSET D_TIME)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GETYEAR (ARTIST TYPE OF D_VC256,
TITLE TYPE OF D_VC256)
RETURNS (AYEAR D_VC10)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_ENERGY (STARTDATE D_TIMESTAMP,
ENDDATE D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
WATT D_DOUBLE)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_PRODUCTION (STARTDATE D_TIMESTAMP,
ENDDATE D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
WATT D_DOUBLE)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_WEATHER (STARTTIME TYPE OF D_TIMESTAMP,
ENDTIME TYPE OF D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
TEMP D_DOUBLE,
DEW_POINT D_DOUBLE,
HUM D_INT,
WIND D_DOUBLE,
WIND_GUST D_DOUBLE,
RAIN D_DOUBLE,
RAIN_RATE D_DOUBLE,
PRESSURE D_DOUBLE,
UV_INDEX D_INT)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE IV (DIFF INTEGER,
STARTTIME TIMESTAMP)
RETURNS (POS VARCHAR(100) CHARACTER SET UTF8,
ARTIST VARCHAR(100) CHARACTER SET UTF8,
TITLE VARCHAR(200) CHARACTER SET UTF8,
LAENGE VARCHAR(100) CHARACTER SET UTF8,
ALBUM VARCHAR(100) CHARACTER SET UTF8)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE MAPMUSICIANS AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE MKALBUMLIST AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE MKARTISTLIST AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE MKPL AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE MKTITLELIST AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE RESET AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE RESETGEN AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE SHOWPL RETURNS (TAG TYPE OF D_VC10,
ZEIT TYPE OF D_TIMESTAMP,
ARTIST TYPE OF D_VC256,
TITLE TYPE OF D_VC256,
ALBUM TYPE OF D_VC256,
JPC TYPE OF D_VC256)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE SPLIT_STRING (P_STRING TYPE OF D_VCLONG,
P_SPLITTER CHAR(1) CHARACTER SET UTF8)
RETURNS (PART TYPE OF D_VCLONG)
AS 
BEGIN SUSPEND; END ^

CREATE OR ALTER PROCEDURE TITLELISTBYID (AID D_FK)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE TITLESLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE TOCSV RETURNS (CSVOUT TYPE OF D_VC1024)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE UPDATEPL AS 
BEGIN EXIT; END ^

SET TERM ; ^
COMMIT WORK;


/*  Index definitions for all user tables */
CREATE INDEX ALBUMS_IDX1 ON ALBUMS (NAME);
CREATE INDEX ALLFRAMES_IDX1 ON ALLFRAMES (FRAME);
CREATE INDEX ARTISTS_IDX1 ON ARTISTS (NAME);
CREATE INDEX HISTORY_IDX1 ON HISTORY (TNR);
CREATE DESCENDING INDEX HISTORY_IDX2 ON HISTORY (ID);
CREATE INDEX HISTORY_IDX3 ON HISTORY (ZEIT);
CREATE DESCENDING INDEX ID_DESC ON IMAGES (ID);
CREATE INDEX IMAGES_IDX1 ON IMAGES (HINT);
CREATE INDEX IMAGES_IDX2 ON IMAGES (CRC32);
CREATE UNIQUE INDEX IUSERS_IDX1 ON IUSERS (NAME);
CREATE INDEX TRACKS_IDX1 ON TRACKS (VOTES);
CREATE INDEX TRACKS_NAME_IDX ON TRACKS (TITLE);
CREATE INDEX ALBUMS_IDX2 ON "cddbALBUMS" (PYEAR);
CREATE INDEX "IDX_cddbALBUMS_1" ON "cddbALBUMS" (NAME);
CREATE INDEX "IDX_cddbARTISTS_1" ON "cddbARTISTS" (NAME);

ALTER TABLE ACTPOS ADD CONSTRAINT FK_ACTPOS_1 FOREIGN KEY (FKRADIO) REFERENCES SYSDATA (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ACT_TRACK ADD CONSTRAINT FK_ACT_TRACK_1 FOREIGN KEY (TNR) REFERENCES TRACKS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ALBUMS ADD CONSTRAINT FK_ALBUMIMAGE FOREIGN KEY (FK_IMAGE) REFERENCES IMAGES (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ALLFRAMES ADD CONSTRAINT FK_ALLFRAMES_1 FOREIGN KEY (FK_IMAGE) REFERENCES IMAGES (ID);

ALTER TABLE ALLFRAMES ADD CONSTRAINT FK_ALLFRAMES_2 FOREIGN KEY (FK_TRACK) REFERENCES TRACKS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ALLFRAMES ADD CONSTRAINT FK_ALLFRAMES_3 FOREIGN KEY (FK_LYRICS) REFERENCES LYRICS (ID);

ALTER TABLE ARTISTS ADD CONSTRAINT FK_ARTISTIMAGE FOREIGN KEY (FK_IMAGE) REFERENCES IMAGES (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE HISTORY ADD CONSTRAINT FK_HISTORY_1 FOREIGN KEY (TNR) REFERENCES TRACKS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ID3_TAGS ADD CONSTRAINT FK_ID3_TAGS_1 FOREIGN KEY (GROUP_ID) REFERENCES ID3_TYPES (ID);

ALTER TABLE PARTICIPANTS ADD CONSTRAINT FK_PARTICIPANTS_1 FOREIGN KEY (FK_TRACK) REFERENCES TRACKS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PARTICIPANTS ADD CONSTRAINT FK_PARTICIPANTS_2 FOREIGN KEY (FK_WHAT) REFERENCES TASK (ID);

ALTER TABLE PARTICIPANTS ADD CONSTRAINT FK_PARTICIPANTS_3 FOREIGN KEY (FK_WHO) REFERENCES MUSICIANS (ID);

ALTER TABLE PL ADD CONSTRAINT FK_PL_1 FOREIGN KEY (FK_TRACK) REFERENCES TRACKS (ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRACKS ADD CONSTRAINT FK_TRACKS_1 FOREIGN KEY (IMAGE_PK) REFERENCES IMAGES (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE TRACKS ADD FOREIGN KEY (LYRICS_PK) REFERENCES LYRICS (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE TRACKS ADD FOREIGN KEY (ALBUM_PK) REFERENCES ALBUMS (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE TRACKS ADD FOREIGN KEY (ARTIST_PK) REFERENCES ARTISTS (ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "cddbALBUMS" ADD CONSTRAINT FK_CDDBALBUMS_1 FOREIGN KEY (FK_ARTIST) REFERENCES "cddbARTISTS" (ID);

COMMIT WORK;

SET TERM ^ ;

/* Stored functions bodies */

ALTER FUNCTION ACTARTIST RETURNS D_VC256
AS 
begin
    return (  select coalesce(a.name,'unknown') from tracks t join artists a on t.artist_pk=a.id  where t.id = tnr(1));
  end ^

ALTER FUNCTION ACTNAME RETURNS D_VC256
AS 
begin
  return (select
              coalesce(AL.NAME, 'unknown') || ' (' || coalesce(T.PYEAR, 'unknown')||') - ' || coalesce(A.NAME, 'unknown') || ' - ' || coalesce(T.TITLE, 'unknown')
          from TRACKS T
          join
              ARTISTS A on T.ARTIST_PK = A.ID
          join
              ALBUMS AL on al.ID = T.ALBUM_PK
          where
              T.ID = TNR(1));
end ^

ALTER FUNCTION ACTTIME RETURNS D_VC40
AS 
begin
    return (select extract(day from current_timestamp)||'.'||extract(month from current_timestamp)||'.'||extract(year from current_timestamp)||' '|| substring(cast(localtime as varchar (13)) from 1 for 5) from rdb$database);
  end ^

ALTER FUNCTION ACTTITLE RETURNS D_VC256
AS 
begin
    return( select coalesce(t.title,'unknown') from tracks t  where t.id = tnr(1));
  end ^

ALTER FUNCTION ACTTRACK RETURNS D_VC256
AS 
begin
    return (select t.path from tracks t where t.id = tnr(1));
end ^




ALTER FUNCTION DAYNAME RETURNS CHAR(2) CHARACTER SET UTF8
AS 
begin
  return 
    CASE extract(WEEKDAY from current_timestamp)
      WHEN 0 THEN 'So'
      when 1 then 'Mo'
      WHEN 2 THEN 'Di'
      when 3 then 'Mi'
      WHEN 4 THEN 'Do'
      when 5 then 'Fr'
      WHEN 6 THEN 'Sa'

end;
end ^


ALTER FUNCTION NEXTPAUSE RETURNS D_VC256
AS 
declare variable SLEN D_SMALLINT;
declare variable SDUR D_SMALLINT;
declare variable ACTPATH D_VC256;
begin
  select S.SILENCE
  from SYSDATA S
  where ID = 1
  into :SLEN;
  select coalesce(D.DURATION, 0)
  from NDELAY D
  where ID = 1
  into :SDUR;
  if (SDUR = 0) then
  begin
    update or insert into NDELAY (ID, DURATION)
    values (1, :SLEN)
    matching (ID);
    ACTPATH = NEXTTRACK();
  end
  else
  begin
    SDUR = SDUR - 1;
    ACTPATH = '/var/data/music/silence.mp3';
    update or insert into NDELAY (ID, DURATION)
    values (1, :SDUR)
    matching (ID);
  end
  return ACTPATH;
end ^

ALTER FUNCTION NEXTTRACK RETURNS D_VC256
AS 
DECLARE M D_FK;
DECLARE A D_FK;
DECLARE MW D_FK;
DECLARE WP D_FK;
DECLARE ACTPATH D_VC256;
DECLARE NTNR D_FK;
begin
  select S.PLMAX
  from SYSDATA S
  where ID = 1
  into :M;
  select max(ID)
  from WL
  into :MW;
  if (:MW is null) then --wishlist is empty
    update ACTPOS
    set WP = null;
  select first 1 WP,
                 AP
  from ACTPOS
  into :WP, :A;
  if (WP is null) then
  begin
    if (A = M) then
    begin
      A = 1;
    end
    else
      A = A + 1;
    update ACTPOS
    set AP = :A;
  end
  else
  begin
    if (WP = MW) then
    begin
      WP = null;
    end
    else
      WP = WP + 1;
    update ACTPOS
    set WP = :WP;
  end
  NTNR = TNR(1);
  select coalesce(T.PATH, '/var/data/music/various/J/Je/Jethro_Tull/A_Passion_Play/01-Side_A.mp3')
  from TRACKS T
  where T.ID = :NTNR
  into :ACTPATH;
  insert into HISTORY (TNR, TRACK)
  values (:NTNR, :ACTPATH);
  update or insert into ACT_TRACK (ID, TNR)
  values (1, :NTNR)
  matching (ID);
  return ACTPATH;
end ^

ALTER FUNCTION TNR (RID D_ID)
RETURNS D_FK
AS 
declare variable a d_fk;
   declare variable W D_FK;
  begin
    select first 1 wp,ap from actpos a where a.fkradio=:rid into :w, :a;
    if ((W is not null) and (w<>0) and exists(select wl.fk_track  from wl where wl.id =:w)) then
      return (select wl.fk_track  from wl where wl.id =:w);
    else
      return (select pl.fk_track  from pl where pl.id =:a);

  end ^


ALTER FUNCTION TO_DATE (DATESTR CHAR(10) CHARACTER SET UTF8)
RETURNS DATE
AS 
begin
 return :datestr;
end ^


COMMIT WORK^



/* Stored procedures bodies */

ALTER PROCEDURE ADDPNGIMAGE (IMAGE D_IMAGE,
AID D_ID,
OVERWRITE D_BOOLEAN = false)
AS 
declare variable FK_IMAGE D_FK;
declare variable ID D_FK;
begin
  /* Procedure Text */
  FK_IMAGE = null;
  select A.FK_IMAGE
  from ARTISTS A
  where A.ID = :AID
  into :FK_IMAGE;
  if (FK_IMAGE is null) then
  begin
    insert into IMAGES (source, IMAGE, MIMETYPE)
    values ('' ,:IMAGE, 'png')
    returning ID
    into :ID;
    update artists a set a.fk_image=:ID where a.id=:aid;
  end
  else
  if (:overwrite) then
  begin
    update images i set i.image=:image where i.id=:fk_image;
  end
end ^

ALTER PROCEDURE ALBUMLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
declare variable ID D_FK;
declare variable FK_TRACK D_FK;

begin
     delete from wl;
     for select row_number() over (order by atr.number),  atr.id from  tracks atr join albums a  on atr.album_pk =a.id where a.name=:NAME into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
    update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE ALBUMLISTBYID (AID D_FK)
AS 
DECLARE ID D_FK;
DECLARE FK_TRACK D_FK;
begin
     delete from wl;
     for select row_number() over (order by atr.number),  atr.id from  tracks atr join albums a  on atr.album_pk =a.id where a.id=:aid into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
    update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE ARTISTLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
declare variable id d_fk;
  declare variable fk_track d_fk;
  declare variable tnr d_fk;
  begin
     delete from wl;
     for select row_number() over (order by t.id),  t.id from tracks t  join artists a on a.id=t.artist_pk where a.name=:NAME into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
    update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE ARTISTLISTBYID (AID D_FK)
AS 
DECLARE id D_FK;
DECLARE fk_track D_FK;
begin
     delete from wl;
     for select row_number() over (order by t.id),  t.id from tracks t  join artists a on a.id=t.artist_pk where a.ID=:AID into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
    update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE BEW (INCVAL TYPE OF D_BIGINT)
AS 
declare variable TID D_FK;
begin
  TID=tnr(1);
  update tracks t set t.votes=t.votes+coalesce(:incval,0) where t.id=:TID;
end ^

ALTER PROCEDURE DECPOS AS 
declare variable m d_fk;
  declare variable a d_fk;
  declare variable mw d_fk;
  declare variable wp d_fk;
  begin
    select first 1 wp,ap from actpos into :wp,:a;
    if (wp is null) then
    begin
      update actpos set ap=ap-2;
    end
    else
    begin
       update actpos set wp=wp-2;
    end
  end ^

ALTER PROCEDURE DROP_ALL AS 
begin
  delete from pl;
  delete from wl;
  delete from artists;
  delete from albums;
  delete from images i where i.id>=0;
  delete from tracks;
  --ALTER TABLE TRACKS ALTER ID RESTART WITH 0;
  --ALTER TABLE artists ALTER COLUMN ID RESTART WITH 0;
  --ALTER TABLE albums ALTER COLUMN ID RESTART WITH 0;
  --ALTER TABLE images ALTER COLUMN ID RESTART WITH 0;
end ^

ALTER PROCEDURE FILLHINT AS 
declare variable VAL type of D_VCLONG;
declare variable HINT type of D_VCLONG;
declare variable CNT type of D_INT;
declare variable source type of D_VCLONG;
declare variable ID type of D_FK;
begin
  for select
          substring(I.source from 23 for 100),
          I.ID
      from IMAGES I
      where
          I.HINT is null
          and I.source starting with '/var/data/music/tidal' into :source, :ID do
  begin
    CNT = 0;
    HINT = '';
    for select
            trim(PART)
        from SPLIT_STRING(:source, '/') into :VAL do
    begin
      if (CNT < 2) then begin
        CNT = CNT + 1;
        HINT = HINT || VAL;
        if (CNT = 1) then begin
          HINT = HINT || ': ';
        end
      end
      update images i set i.hint = :hint where i.id=:id;
    end
  end
end ^

ALTER PROCEDURE FILLYEARS RETURNS (YYEAR TYPE OF D_SMALLINT)
AS 
declare variable ALYEAR type of D_SMALLINT;
declare variable ALBUM_ID type of D_FK;
declare variable ARTIST type of D_VC256;
declare variable TITLE type of D_VC256;
begin
  /* Procedure Text */
  for select first 50 skip 0 ID,
                      NAME,
                      ARTIST
      from ALBUMS
      into :ALBUM_ID, :TITLE, :ARTIST
  do
  begin
    for select AYEAR
        from GETYEAR(:ARTIST, :TITLE)
        into :YYEAR
    do
    begin
      suspend;
      if (YYEAR > 0) then
        update ALBUMS A
        set PYEAR = :YYEAR
        where A.ID = :ALBUM_ID;
    end
  end
end ^

ALTER PROCEDURE GETMETA RETURNS (TITLE D_VC256,
ARTIST D_VC256,
ALBUM D_VC256,
LEN D_INT,
PYEAR D_VC128,
PERCENT D_INT,
ATIME D_INT,
IMGSRC D_VC256,
IMG D_IMAGE,
TEMP D_DOUBLE,
HUM D_DOUBLE,
WIND D_DOUBLE,
VERBRAUCH D_DOUBLE,
PRODUKTION D_DOUBLE,
CINFO D_VC128)
AS 
DECLARE T D_TIME;
DECLARE TID D_FK;
DECLARE RID D_FK;
DECLARE WINFO D_BOOLEAN;
DECLARE WURL D_VC128;
DECLARE SURL D_VC128;
DECLARE WUSER D_VC32;
DECLARE WPW D_VC32;
DECLARE SUSER D_VC32;
DECLARE SPW D_VC32;
begin
  select first 1
      STARTTIME
  from ACT_TRACK into :T;
  RID = 1;
  TEMP = 0;
  HUM = 0;
  WIND = 0;
  select
      TR.TNR
  from ACT_TRACK TR
  where
      TR.ID = 1 into :TID;
  --TID = TNR(:RID);
  select
      coalesce(A.NAME, 'unknown'),
      coalesce(T.TITLE, 'unknown'),
      coalesce(AL.NAME, 'unknown'),
      coalesce(T.LEN, 60) + coalesce(S.SILENCE, 0),
      coalesce(coalesce(T.PYEAR, AL.PYEAR), 'unknown'),
      case S.IMGSRC
        when 1 then coalesce(coalesce(ARI.MIMETYPE, ARA.MIMETYPE, ART.MIMETYPE), UK.MIMETYPE)
        when 2 then coalesce(coalesce(ART.MIMETYPE, ARA.MIMETYPE, ARI.MIMETYPE), UK.MIMETYPE)
        else coalesce(coalesce(ARA.MIMETYPE, ARI.MIMETYPE, ART.MIMETYPE), UK.MIMETYPE)
      end,
      case S.IMGSRC
        when 1 then coalesce(coalesce(ARI.IMAGE, ARA.IMAGE, ART.IMAGE), UK.IMAGE)
        when 2 then coalesce(coalesce(ART.IMAGE, ARA.IMAGE, ARI.IMAGE), UK.IMAGE)
        else coalesce(coalesce(ARA.IMAGE, ARI.IMAGE, ART.IMAGE), UK.IMAGE)
      end
  from TRACKS T
  join
      ARTISTS A on T.ARTIST_PK = A.ID
  left join
      ALBUMS AL on T.ALBUM_PK = AL.ID
  left join
      IMAGES ARI on A.FK_IMAGE = ARI.ID
  left join
      IMAGES ARA on AL.FK_IMAGE = ARA.ID
  left join
      IMAGES ART on T.IMAGE_PK = ART.ID
  left join
      IMAGES UK on UK.ID = -1
  left join
      SYSDATA S on S.ID = :RID
  where
      T.ID = :TID into :ARTIST, :TITLE, :ALBUM, :LEN, :PYEAR, :IMGSRC, :IMG;
  ATIME = datediff(second from :T to localtime);
  PERCENT = ATIME * 100 / LEN;
  select
      WEATHER,WURL,SURL
  from SYSDATA S
  where
      S.ID = :RID into :WINFO,:WURL,:SURL;
  if (:WINFO) then begin
    execute statement 'select first 1 TEMP, HUM, bft(WIND)  from METEO M  order by M.id desc'
        on external :WURL
        as user :WUSER password :WPW
        with common transaction
        into :TEMP, :HUM, :WIND;
    execute statement 'select v.kwh from aktuellerverbrauch v'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :VERBRAUCH;
    execute statement 'select s.watt from aktuelleproduktion s'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :PRODUKTION;
    execute statement 'select first 1 ''Batterie: ''||BATTERYLEVEL||''%,''||     case CHARGINGSTATUS when 1.0 then '' lädt,'' else  '' lädt nicht,'' end|| case plugstatus when 1.0 then '' verbunden, '' else   '' nicht verbunden, '' end||     ''Reichweite: ''||round(bs.batteryautonomy,1)||'' Km |''|| ''Benzin: ''||round(cp.fuelquantity,1)||''l, Reichweite: ''||round(cp.fuelautonomy,1)||'' Km | ''     ||cp.ts from BATTERYSTATUS bs join cockpit cp on cp.id=bs.id  order by cp.id desc'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :CINFO;
    when any   do
    begin

    end
  end
  SUSpEND;
end ^

ALTER PROCEDURE GETMETA2 RETURNS (TITLE D_VC256,
ARTIST D_VC256,
ALBUM D_VC256,
LEN D_INT,
PYEAR D_VC128,
PERCENT D_INT,
ATIME D_INT,
IMGSRC D_VC256,
IMG D_IMAGE,
TEMP D_DOUBLE,
HUM D_DOUBLE,
WIND D_DOUBLE,
VERBRAUCH D_DOUBLE,
PRODUKTION D_DOUBLE,
CINFO D_VC128)
AS 
DECLARE T D_TIME;
DECLARE TID D_FK;
DECLARE RID D_FK;
DECLARE WINFO D_BOOLEAN;
DECLARE WURL D_VC128;
DECLARE SURL D_VC128;
DECLARE WUSER D_VC32;
DECLARE WPW D_VC32;
DECLARE SUSER D_VC32;
DECLARE SPW D_VC32;
begin
   select first 1
       TITLE,
       ARTIST,
       ALBUM,
       GONE,
       LEN,
       PYEAR,
       IMGSRC,
       IMG
   from TIDALINFO into :TITLE, :ARTIST, :ALBUM, :percent, :LEN, :PYEAR, :IMGSRC, :IMG;


  RID = 1;
  TEMP = 0;
  HUM = 0;
  WIND = 0;
  select
      WEATHER
  from SYSDATA S
  where
      S.ID = :RID into :WINFO;
  if (:WINFO) then begin
    execute statement 'select first 1 TEMP, HUM, bft(WIND)  from METEO M  order by M.id desc'
        on external :WURL
        as user :WUSER password :WPW
        with common transaction
        into :TEMP, :HUM, :WIND;
    execute statement 'select v.kwh from aktuellerverbrauch v'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :VERBRAUCH;
    execute statement 'select s.watt from aktuelleproduktion s'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :PRODUKTION;
    execute statement 'select first 1 ''Batterie: ''||BATTERYLEVEL||''%,''||     case CHARGINGSTATUS when 1.0 then '' lädt,'' else  '' lädt nicht,'' end|| case plugstatus when 1.0 then '' verbunden, '' else   '' nicht verbunden, '' end||     ''Reichweite: ''||round(bs.batteryautonomy,1)||'' Km |''|| ''Benzin: ''||round(cp.fuelquantity,1)||''l, Reichweite: ''||round(cp.fuelautonomy,1)||'' Km | ''     ||cp.ts from BATTERYSTATUS bs join cockpit cp on cp.id=bs.id  order by cp.id desc'
        on external :SURL
        as user :SUSER password :SPW
        with common transaction
        into :CINFO;
    when any   do
    begin

    end
  end
  SUSpEND;
end ^

ALTER PROCEDURE GETSUN RETURNS (SUNRISE D_TIME,
SUNSET D_TIME)
AS 
declare variable WINFO D_BOOLEAN;
declare variable RID D_FK;
declare variable WURL D_VC1024;
DECLARE WUSER D_VC32;
DECLARE WPW D_VC32;

begin
   RID = 1;
   select weather,wurl,wuser,wpw from sysdata s where s.id= :rid into :winfo, :wurl , :WUSER, :WPW;

   if (:winfo) then
   begin
   execute statement 'select s.sunrise, s.sunset from sun s where s.datum = current_date'
      on external :wurl
      as user :WUSER password :WPW
      with common transaction
      into :SUNRISE, :SUNSET;
    if ((:sunrise is null) or (:sunset is null))  then
    execute statement 'select s.sunrise, s.sunset from sun s where s.datum = current_date-1'
      on external :wurl
      as user :WUSER password :WPW
      with common transaction
      into :SUNRISE, :SUNSET;

    when any
    do
    begin
     select null,null from rdb$database into :sunrise,:sunset;
    end
   end

  suspend;
end ^

ALTER PROCEDURE GETYEAR (ARTIST TYPE OF D_VC256,
TITLE TYPE OF D_VC256)
RETURNS (AYEAR D_VC10)
AS 
declare variable yy d_smallint;
begin
 ayear=0;
 for select first 1 al.pyear from "cddbALBUMS" al join "cddbARTISTS" ar on al.fk_artist=ar.id
      where al.name containing :title and ar.name containing :artist and al.pyear>0
      order by al.pyear asc
      into :yy
      do
      begin
      if ((yy>0) and (yy<1900)) then
         yy=yy+1900;
      ayear=yy;
  end
  suspend;
end ^

ALTER PROCEDURE GET_ENERGY (STARTDATE D_TIMESTAMP,
ENDDATE D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
WATT D_DOUBLE)
AS 
DECLARE SURL D_VC128;
DECLARE RID D_FK;
DECLARE STMT D_VCLONG;
DECLARE SUSER D_VC32;
DECLARE SPW D_VC32;
BEGIN
RID=1;
select
      SURL,SUSER,SPW
  from SYSDATA S
  where
      S.ID = :RID into :SURL,:SUSER,:SPW;


   stmt='select v.ts, v.wh from verbrauchsdaten v
   where v.ts >= '''||:STARTDATE||''' and v.ts <= '''||:ENDDATE||''' order by v.ts asc';
   for execute statement (stmt) 

    on external :SURL
     as user :SUSER password :SPW
        with common transaction
        into :TIMESTAMP_LOCAL,:WATT
   do
     SUSPEND;
END ^

ALTER PROCEDURE GET_PRODUCTION (STARTDATE D_TIMESTAMP,
ENDDATE D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
WATT D_DOUBLE)
AS 
DECLARE SURL D_VC128;
DECLARE SUSER D_VC32;
DECLARE SPW D_VC32;
DECLARE RID D_FK;
DECLARE STMT D_VCLONG;
BEGIN
RID=1;
select
      SURL,SUSER,SPW
  from SYSDATA S
  where
      S.ID = :RID into :SURL,:SUSER,:SPW;


   stmt='select v.ts, v.ACTPOWER from solar v
   where v.ts >= '''||:STARTDATE||''' and v.ts <= '''||:ENDDATE||''' order by v.ts asc';
   for execute statement (stmt) 

    on external :SURL
     as user :SUSER password :SPW
        with common transaction
        into :TIMESTAMP_LOCAL,:WATT
   do
     SUSPEND;
END ^

ALTER PROCEDURE GET_WEATHER (STARTTIME TYPE OF D_TIMESTAMP,
ENDTIME TYPE OF D_TIMESTAMP)
RETURNS (TIMESTAMP_LOCAL D_TIMESTAMP,
TEMP D_DOUBLE,
DEW_POINT D_DOUBLE,
HUM D_INT,
WIND D_DOUBLE,
WIND_GUST D_DOUBLE,
RAIN D_DOUBLE,
RAIN_RATE D_DOUBLE,
PRESSURE D_DOUBLE,
UV_INDEX D_INT)
AS 
DECLARE WURL D_VC128;
DECLARE WUSER D_VC32;
DECLARE WPW D_VC32;
DECLARE RID D_FK;
DECLARE STMT D_VCLONG;
BEGIN

RID=1;
select
      WURL,WUSER,WPW
  from SYSDATA S
  where
      S.ID = :RID into :WURL,:WUSER,:WPW;

stmt = 
'select m.timestamp_local, m.temp, m.dew_point,
                  m.hum, m.wind,  m.wind_gust,
                  m.rain, m.rain_rate, m.pressure, m.uv_index from meteo m
                   where m.timestamp_local between '''|| :starttime || ''' and ''' || :endtime|| ''' order by m.timestamp_local';
for execute statement (stmt) 

    on external :WURL
     as user :WUSER password :WPW
        with common transaction
        into :TIMESTAMP_LOCAL,:TEMP,:DEW_POINT,
             :HUM,:WIND, :WIND_GUST,
             :RAIN, :RAIN_RATE, :PRESSURE, :UV_INDEX 
 do
     SUSPEND;
         
             

    
END ^

ALTER PROCEDURE IV (DIFF INTEGER,
STARTTIME TIMESTAMP)
RETURNS (POS VARCHAR(100) CHARACTER SET UTF8,
ARTIST VARCHAR(100) CHARACTER SET UTF8,
TITLE VARCHAR(200) CHARACTER SET UTF8,
LAENGE VARCHAR(100) CHARACTER SET UTF8,
ALBUM VARCHAR(100) CHARACTER SET UTF8)
AS 
begin
  diff=coalesce(:diff,0);
  for select first 100
    substring( (dateadd(datediff(second from :starttime to cast(H.ZEIT as timestamp)) second to time '0:00'-:diff) ) from 0 for 9),
    A.NAME,
    T.TITLE,
    substring(dateadd(T.LEN second to time '0:00') from 0 for 9),
    coalesce(AL.NAME, 'unknown')
from HISTORY H
join
    TRACKS T on T.ID = H.TNR
join
    ARTISTS A on T.ARTIST_PK = A.ID
left join
    ALBUMS AL on T.ALBUM_PK = AL.ID
where
    H.ZEIT > :starttime
order by
    H.ID  
    into :pos,:artist,:title,:laenge,:Album
    do

  suspend;
end ^

ALTER PROCEDURE MAPMUSICIANS AS 
declare variable VAL type of D_VCLONG;
declare variable WHO type of D_VCLONG;
declare variable WHOID type of D_FK;
declare variable TID type of D_FK;
declare variable WHATID type of D_FK;
declare variable TYP type of D_SMALLINT;
declare variable WHAT type of D_VCLONG;
declare variable FRAME type of D_VCLONG;
begin
  /* Procedure Text */
  for select f.fk_track, f.content from allframes f where f.frame='TMCL' into :TID,:frame
  do
  begin
    typ=0;
    for select  trim(part) from split_string(:frame, ':') into :val
    do
    begin
      if (typ=0) then
      begin
         typ=1;
         what=:val;
         update or insert into TASK (TASK)
         values (:WHAT)
         matching (TASK) returning id into :whatid ;
      end
      else
      begin
        typ=0;
        who=:val;
        update or insert into MUSICIANS (NAME)
        values (:WHO)
        matching (NAME) returning id into :whoid;

        update or insert into PARTICIPANTS (FK_TRACK, FK_WHAT, FK_WHO)
        values (:TID, :WHATID, :WHOID)
        matching (FK_TRACK,FK_WHAT,FK_WHO);
      end
    end
  end
end ^

ALTER PROCEDURE MKALBUMLIST AS 
declare variable id d_fk;
  declare variable fk_track d_fk;
  declare variable tnr d_fk;
  begin
     tnr=tnr(1);
     delete from wl;
     for select row_number() over (order by atr.number),  atr.id from tracks t  join tracks atr on atr.album_pk =t.album_pk where t.id=:tnr into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
     update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE MKARTISTLIST AS 
declare variable ID D_FK;
declare variable FK_TRACK D_FK;
declare variable TNR D_FK;
begin
  TNR = TNR(1);
  delete from WL;
  for select row_number() over(order by ATR.ID),
             ATR.ID
      from TRACKS T
      join TRACKS ATR on ATR.ARTIST_PK = T.ARTIST_PK
      where T.ID = :TNR
      into :ID, :FK_TRACK
  do
    insert into WL (ID, FK_TRACK)
    values (:ID, :FK_TRACK);
  update ACTPOS
  set WP = 0,
      AP = AP + 1;
end ^

ALTER PROCEDURE MKPL AS 
declare variable ID D_FK;
declare variable FK_TRACK D_FK;
declare variable PLC D_BIGINT;
begin
     delete from actpos;
     delete from pl;
     plc=0;
     for select row_number() over (order by rand()) as rid ,t.id from tracks t where coalesce(t.votes,0)>=-2 into :id,:fk_track
     do
     begin
       insert into pl (id,fk_track) values (:id,:fk_track);
       :plc = :plc+1;
     end
     update sysdata set plmax=:plc;
     insert into actpos (ap) values(1);
  end ^

ALTER PROCEDURE MKTITLELIST AS 
declare variable id d_fk;
  declare variable fk_track d_fk;
  declare variable acttitle d_vc256;
  begin
     acttitle=acttitle();
     delete from wl;
     for select row_number() over (order by t.id),  t.id  from tracks t where t.title containing ( :acttitle) into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
     update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE RESET AS 
begin
     update actpos set wp=null;
  end ^

ALTER PROCEDURE RESETGEN AS 
begin
  execute statement 'ALTER TABLE tracks ALTER COLUMN ID RESTART WITH 1';
  execute statement 'ALTER TABLE artists ALTER COLUMN ID RESTART WITH 1';
  execute statement 'ALTER TABLE albums ALTER COLUMN ID RESTART WITH 1';
  execute statement 'ALTER TABLE images ALTER COLUMN ID RESTART WITH 1';

end ^

ALTER PROCEDURE SHOWPL RETURNS (TAG TYPE OF D_VC10,
ZEIT TYPE OF D_TIMESTAMP,
ARTIST TYPE OF D_VC256,
TITLE TYPE OF D_VC256,
ALBUM TYPE OF D_VC256,
JPC TYPE OF D_VC256)
AS 
DECLARE AP TYPE OF D_BIGINT;
DECLARE CNT TYPE OF D_SMALLINT;
DECLARE WP TYPE OF D_BIGINT;
begin
  /* Procedure Text */
  CNT = 0;
  for select CH,
             ZT,
             NM,
             TT,
             AN
      from (select first 10 '' as CH,
                            H.ZEIT as ZT,
                            A.NAME as NM,
                            T.TITLE as TT,
                            coalesce(AL.NAME, 'unknown') as AN
            from HISTORY H
            join TRACKS T on T.ID = H.TNR
            join ARTISTS A on T.ARTIST_PK = A.ID
            join ALBUMS AL on T.ALBUM_PK = AL.ID
            order by H.ID desc)
      order by ZT
      into :TAG, :ZEIT, :ARTIST, :TITLE, :ALBUM
  do
  begin
    JPC = :ARTIST||' '||:ALBUM;
    JPC = replace(:JPC, ' ', '+');
    CNT = CNT + 1;
    if (CNT = 10) then
      TAG = '>';
    suspend;
  end
  select first 1 WP,
                 AP
  from ACTPOS
  into :WP, :AP;
  if (WP is not null) then
  begin
  for select first 10 ' ',
                      null,
                      A.NAME,
                      T.TITLE,
                      coalesce(AL.NAME, 'unknown')
      from WL P
      join TRACKS T on T.ID = P.FK_TRACK
      join ARTISTS A on A.ID = T.ARTIST_PK
      join ALBUMS AL on T.ALBUM_PK = AL.ID
      where P.ID > :WP
      order by P.ID
      into :TAG, :ZEIT, :ARTIST, :TITLE, :ALBUM
  do
  begin
    JPC = :ARTIST||' '||:ALBUM;
    JPC = replace(:JPC, ' ', '+');
    suspend;
  end
  end
  for select first 10 ' ',
                      null,
                      A.NAME,
                      T.TITLE,
                      coalesce(AL.NAME, 'unknown')
      from pL P
      join TRACKS T on T.ID = P.FK_TRACK
      join ARTISTS A on A.ID = T.ARTIST_PK
      join ALBUMS AL on T.ALBUM_PK = AL.ID
      where P.ID > :AP
      order by P.ID
      into :TAG, :ZEIT, :ARTIST, :TITLE, :ALBUM
  do
  begin
    JPC = :ARTIST||' '||:ALBUM;
    JPC = replace(:JPC, ' ', '+');
    suspend;
  end

end ^

ALTER PROCEDURE SPLIT_STRING (P_STRING TYPE OF D_VCLONG,
P_SPLITTER CHAR(1) CHARACTER SET UTF8)
RETURNS (PART TYPE OF D_VCLONG)
AS 
declare variable lastpos integer;
  declare variable nextpos integer;
begin
    p_string = :p_string || :p_splitter;
    lastpos = 1;
    nextpos = position(:p_splitter, :p_string, lastpos);
    if (lastpos = nextpos) then
        begin
            part = substring(:p_string from :lastpos for :nextpos - :lastpos);
            suspend;
            lastpos = :nextpos + 1;
            nextpos = position(:p_splitter, :p_string, lastpos);
        end
    while (:nextpos > 1) do
        begin
            part = substring(:p_string from :lastpos for :nextpos - :lastpos);
            lastpos = :nextpos + 1;
            nextpos = position(:p_splitter, :p_string, lastpos);
            suspend;
        end
end ^

ALTER PROCEDURE TITLELISTBYID (AID D_FK)
AS 
begin
    delete from wl;
    insert into wl (id,fk_track) values (1,:aid);
    update actpos set wp=0,ap=ap+1;
  end ^

ALTER PROCEDURE TITLESLIST (NAME VARCHAR(128) CHARACTER SET UTF8)
AS 
declare variable ID D_FK;
declare variable FK_TRACK D_FK;
declare variable TNR D_FK;
begin
     delete from wl;
     for select row_number() over (order by t.id),  t.id from tracks t where t.title containing(:NAME) into :id,:fk_track
     do
       insert into wl (id,fk_track) values (:id,:fk_track);
    update actpos set wp=0,ap=ap+1;
end ^

ALTER PROCEDURE TOCSV RETURNS (CSVOUT TYPE OF D_VC1024)
AS 
begin
for select '"'||A.NAME||'";"'||T.TITLE||'";"'||coalesce(AL.NAME,'unknown')||'";"'||substring(T.PATH from 20)||'"'
from
    TRACKS T
join
    ARTISTS A on T.ARTIST_PK = A.ID
left join
    ALBUMS AL on T.ALBUM_PK = AL.ID
--where A.name='Hozier'
order by
    a.name, coalesce(al.name,'unknown'),t.number,  t.title
    into :CSVout do
  suspend;
end ^

ALTER PROCEDURE UPDATEPL AS 
declare variable PLC type of D_BIGINT;
declare variable TC type of D_BIGINT;
begin
  select count(t.votes) from tracks t where coalesce(t.votes,0)>=-2 into :tc;
  select count (*) from pl into :plc;
  if (tc<>plc) then
     execute procedure mkpl;
end ^

SET TERM ; ^
COMMIT WORK;


/* Table constraints */

ALTER TABLE ACT_TRACK ADD 
        CHECK (ID=1);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER ACTPOS_BIU0 FOR ACTPOS 
ACTIVE BEFORE INSERT OR UPDATE POSITION 0 
AS
begin
  new.starttime=localtime ;
end ^

CREATE TRIGGER ACT_TRACK_BIU0 FOR ACT_TRACK 
ACTIVE BEFORE INSERT OR UPDATE POSITION 0 
AS
begin
  new.starttime=localtime ;
end ^

CREATE TRIGGER IMAGES_BIU0 FOR IMAGES 
ACTIVE BEFORE INSERT OR UPDATE POSITION 0 
AS
begin
   new.crc32=hash(new.image using crc32);
   new.added= current_timestamp;
  /* Trigger text */
end ^

CREATE TRIGGER RADIOS_AIU0 FOR RADIOS 
ACTIVE AFTER INSERT OR UPDATE POSITION 0 
AS
begin
   update or insert into SYSDATA (id)
   values (new.id)
   matching (id);
end ^


SET TERM ; ^
COMMIT WORK;

/* Grant permissions for this database */
GRANT ALL ON ACTPOS TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON ACTPOS TO USER SHIVA WITH GRANT OPTION;
GRANT SELECT, UPDATE ON ACTPOS TO PROCEDURE TITLESLIST;
GRANT SELECT ON ACTPOS TO FUNCTION TNR;
GRANT SELECT ON ACT_TRACK TO PROCEDURE GETMETA;
GRANT ALL ON ACT_TRACK TO USER SHIVA;
GRANT ALL ON ALBUMS TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON ALBUMS TO USER SHIVA WITH GRANT OPTION;
GRANT ALL ON ALLFRAMES TO USER SHIVA;
GRANT ALL ON ARTISTS TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON ARTISTS TO USER SHIVA WITH GRANT OPTION;
GRANT ALL ON FORMAT TO USER SHIVA;
GRANT ALL ON HISTORY TO USER SHIVA WITH GRANT OPTION;
GRANT ALL ON ID3_TAGS TO USER SHIVA;
GRANT ALL ON ID3_TYPES TO USER SHIVA;
GRANT ALL ON IMAGES TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON IMAGES TO USER SHIVA WITH GRANT OPTION;
GRANT ALL ON IUSERS TO PUBLIC;
GRANT ALL ON IUSERS TO USER SHIVA;
GRANT ALL ON LYRICS TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON LYRICS TO USER SHIVA WITH GRANT OPTION;
GRANT ALL ON MUSICIANS TO USER SHIVA;
GRANT ALL ON MUSIK TO USER SHIVA;
GRANT INSERT, SELECT, UPDATE ON NDELAY TO FUNCTION NEXTPAUSE;
GRANT ALL ON NDELAY TO USER SHIVA;
GRANT ALL ON PARTICIPANTS TO USER SHIVA;
GRANT ALL ON PL TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON PL TO USER SHIVA WITH GRANT OPTION;
GRANT SELECT ON PL TO FUNCTION TNR;
GRANT ALL ON RADIOS TO USER SHIVA;
GRANT ALL ON SESSIONS TO USER SHIVA WITH GRANT OPTION;
GRANT SELECT ON SYSDATA TO FUNCTION NEXTPAUSE;
GRANT ALL ON SYSDATA TO USER SHIVA;
GRANT ALL ON TASK TO USER SHIVA;
GRANT ALL ON TIDALINFO TO PUBLIC;
GRANT ALL ON TIDALINFO TO USER SHIVA;
GRANT ALL ON TRACKS TO PUBLIC;
GRANT ALL ON TRACKS TO USER SHIVA WITH GRANT OPTION;
GRANT SELECT ON TRACKS TO PROCEDURE TITLESLIST;
GRANT ALL ON WL TO PUBLIC WITH GRANT OPTION;
GRANT ALL ON WL TO USER SHIVA WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT ON WL TO PROCEDURE TITLESLIST;
GRANT SELECT ON WL TO FUNCTION TNR;
GRANT SELECT ON "cddbALBUMS" TO PROCEDURE GETYEAR;
GRANT SELECT ON "cddbARTISTS" TO PROCEDURE GETYEAR;
GRANT EXECUTE ON PROCEDURE ADDPNGIMAGE TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE ALBUMLIST TO PUBLIC WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE ALBUMLIST TO USER SHIVA WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE ALBUMLISTBYID TO USER SHIVA WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE ARTISTLIST TO PUBLIC WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE ARTISTLIST TO USER SHIVA WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE ARTISTLISTBYID TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE BEW TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE DECPOS TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE DROP_ALL TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE FILLYEARS TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GETMETA TO PUBLIC WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GETMETA TO USER SHIVA WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GETMETA2 TO PUBLIC;
GRANT EXECUTE ON PROCEDURE GETMETA2 TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GETSUN TO PUBLIC;
GRANT EXECUTE ON PROCEDURE GETSUN TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GETYEAR TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GET_ENERGY TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GET_PRODUCTION TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE GET_WEATHER TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE IV TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE MAPMUSICIANS TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE MKALBUMLIST TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE MKARTISTLIST TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE MKPL TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE MKTITLELIST TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE RESET TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE RESETGEN TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE SHOWPL TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE SPLIT_STRING TO USER SHIVA;

GRANT EXECUTE ON PROCEDURE TITLELISTBYID TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE TITLESLIST TO PUBLIC;
GRANT EXECUTE ON PROCEDURE TITLESLIST TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE TOCSV TO USER SHIVA;
GRANT EXECUTE ON PROCEDURE UPDATEPL TO USER SHIVA;
GRANT EXECUTE ON FUNCTION ACTARTIST TO USER SHIVA;
GRANT EXECUTE ON FUNCTION ACTNAME TO USER SHIVA;
GRANT EXECUTE ON FUNCTION ACTTIME TO USER SHIVA;
GRANT EXECUTE ON FUNCTION ACTTITLE TO USER SHIVA;
GRANT EXECUTE ON FUNCTION ACTTRACK TO USER SHIVA;
GRANT EXECUTE ON FUNCTION DAYNAME TO USER SHIVA;
GRANT EXECUTE ON FUNCTION NEXTPAUSE TO USER SHIVA;
GRANT EXECUTE ON FUNCTION NEXTTRACK TO FUNCTION NEXTPAUSE;
GRANT EXECUTE ON FUNCTION NEXTTRACK TO USER SHIVA;
GRANT EXECUTE ON FUNCTION TNR TO USER SHIVA;
GRANT USAGE ON SEQUENCE RDB$1 TO USER SHIVA WITH GRANT OPTION;
commit work;

INSERT INTO SYSDATA (
	ID,
	PLMAX,
	WLMAX,
	IMGSRC,
	WEATHER,
	SILENCE,
	WURL,
	SURL,
    SUSER,
    SPW,
    WUSER,
    WPW
) VALUES (
	1,
	16429,
	NULL,
	0,
	false,
	5,
	'192.168.178.201:weather',
	'192.168.178.201:strom',
    'SYSDBA',
    'masterkey',
    'SYSDBA',
    'masterkey'
);


INSERT INTO RADIOS (
	ID,
	NAME
) VALUES (
	1,
	'docker'
);

INSERT INTO IUSERS (
	ID,
	NAME,
	PASSWORD,
	IADMIN
) VALUES (
	1,
	'shiva',
	'shiva',
	1
);




commit work;

